### ISSUE TITLE
VulkanApplicationInfo

### ISSUE THREAD

**Issue by schecko** [MDBijman/Vulkan-Renderer#1]
Tried running, but to make instance creation successful I had to add:
applicationInfo.apiVersion = VK_MAKE_VERSION(1, 0, 2);
in your VulkanInstance class.
Afterwords, the shader broke somewhere but I gotta to to sleep.

**Comment by MDBijman** [comment]
I added an apiVersion setter to the VulkanInstance wrapper, and set it with VK_API_VERSION. This should work for anyone with a version of vk installed. 

The shaders probably didn't work because the path the the files was specific to my machine. I added SHADER_LOCATION, VERTEX_LOCATION, and FRAGMENT_LOCATION strings to VulkanTriangle.h. See if you can get it to work by pointing those to the correct location. They're located in the 'data' folder in the root.

Let me know if you get it working.

**Comment by schecko** [comment]
I fixed the shader location and that seems to be working, but for some reason your wrapper around the applicationinfo struct is not cooperating with VK_API_VERSION or VK_MAKE_VERSION(1, 0, 3);
.setApiVersion(VK_API_VERSION); 
However, if i access the struct manually (applicationInfo.vkInfo.apiVersion = VK_API_VERSION;) it works. it could be something to do with the macro itself? not too sure.
